name: 'appcenter-build'
description: 'Set and run build on AppCenter'
inputs:
  appcenter_token:
    required: true
    description: 'AppCenter token to call the API'
  appcenter_user:
    required: true
    description: 'AppCenter user or organization name'
  appcenter_app:
    required: true
    description: 'AppCenter app name'
  branch_name:
    required: true
    description: 'GitHub branch name to be used as a source for the build'
  settings_branch_name:
    required: true
    description: 'GitHub branch name to be used as a source on AppCenter for the build settings'
runs:
  using: 'node16'
  main: 'dist/index.js'
